{% set name = "msal" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51b8e8e0d918d9b4813f006324e7c4e21eb76268dd4c1a06d811a3475ad4ac57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests >=2.0.0,<3
    - pyjwt >=1.0.0,<2

test:
  imports:
    - msal
    - msal.oauth2cli

about:
  home: https://github.com/AzureAD/microsoft-authentication-library-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Authentication Library (MSAL) for Python makes it easy to authenticate to Azure Active Directory

  description: |
    The MSAL library for Python enables your app to access the Microsoft Cloud by supporting
    authentication of users with Microsoft Azure Active Directory accounts and Microsoft Accounts
    using industry standard OAuth2 and OpenID Connect.
  doc_url: https://msal-python.readthedocs.io
  dev_url: https://github.com/AzureAD/microsoft-authentication-library-for-python

extra:
  recipe-maintainers:
    - roederja2
