travis:
  secure:
    BINSTAR_TOKEN: FwEghvQgraTJ34PCVZse+SM6GDML0PppoF55f7uUiKBRBS7XZ5fKUEHNoQa8Xi1rJzQjsjMeUWuHBT68udn7Nj9V7vkdWqfr7OSNwySFuNZxMpu2gmMBtsDyDXdU+ythzE+M57CLq+Q9GkkyrZOQuKQ8pBsq/5xTEIJ3kCcaf5URigFJ9xX2eyT+jif+ZylsC9zLFOToEZLoNArVwnmklC87Z5qRtc62OcvBermlgpHqx2zpEOeNk6vMJwXKhmMlBnLXnr5jeJPnHUaAUjsOsNn0aGGzlLgt25mzIUR7CCVQ8mLOn5h+pMsT5BBCEm76B+BnYzMQ3heUYFqy6RG/kv+w4s9+KAGHAEH9ksFqVXvYj/Q8aMufq9KBtSkJLhG0pf7I+1nL6PkjpZyrwteHLAnjO0N/Lh7fKMEd92Hk4PYqVabq2XXZ02fH2WOQbPa8xh2pW2MNF0ntFexjbVfANBdyssdSLWJvg8HAvOqGcz3JC5DpW0ksiqpjc4/TS9t/lCuRoK8XFd7UipbhZ9fEsWpZ8u970SpD05vVwKQXd92c4/YFYNpIfc7rM96audFknwnzhZZVK4OKvddRUJzMPnvGOGwhkLtO268EVJGjAN9RgIpEWuXKh5eToDkxsxcua+SC2AxJ7+ARHQ1w2YKbGSj1tTqs97+clE46yPg+j74=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
